name: Chess Workflow

on:
  issue_comment:
    types: [created]
    issues: [1]

jobs:
  Make-a-move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get chess move notation from comment
        run: |
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          echo "${{ github.event.comment.user.login }} wants to move ${{ github.event.comment.body }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Generate Chessboard Image
        run: |
          python scripts/export_chessboard.py $COMMENT_BODY
          TIMESTAMP=$(date +%s)
          sed -i 's|\(<img src="https://raw.githubusercontent.com/thieleju/thieleju/main/images/chessboard.png\)\(\?v=[^"]*\)\?"|\1?v=$TIMESTAMP"|g' README.md

      - name: Upload Chessboard Image
        uses: actions/upload-artifact@v2
        with:
          name: chessboard-image
          path: images/chessboard.png

      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `@${{ github.event.comment.user.login }} played the move ${{ github.event.comment.body }}`
            })

      - name: Update readme link and commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add images/chessboard.png fen.txt README.md
          git commit -m "🚀 Update chessboard image, fen and readme"
          git push origin HEAD
