name: Chess Workflow

on:
  issue_comment:
    types: [created]
    issues:
      - 1

jobs:
  issueCommentJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get issue comment body
        id: extract_comment
        run: |
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV

      - name: Output comment content
        run: |
          echo "The comment content is: $COMMENT_BODY"
