name: Chess Workflow

on:
  issue_comment:
    types: [created]
    issues: [1]

jobs:
  Make-a-move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get chess move notation from comment
        run: |
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          echo "${{ github.event.comment.user.login }} wants to move ${{ github.event.comment.body }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Generate Chessboard Image
        run: |
          python scripts/export_chessboard.py $COMMENT_BODY

      - name: Upload Chessboard Image
        uses: actions/upload-artifact@v2
        with:
          name: chessboard-image
          path: images/chessboard.png

      - name: Get Artifact URL
        id: get_artifact_url
        run: echo "url=$(echo ${{ github.run_id }}/artifacts/download?path=chessboard-image)" >> $GITHUB_ENV

      - name: Comment with Chessboard Image
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Chessboard image\n![Chessboard](${{ env.url }})'
            });
          user-agent: actions/github-script
          result-encoding: json
