name: Chess Workflow

on:
  issue_comment:
    types: [created]
    issues: [1]

jobs:
  Make-a-move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get chess move notation from comment
        run: |
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          echo "${{ github.event.comment.user.login }} wants to move ${{ github.event.comment.body }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Generate Chessboard Image
        run: |
          # delete all other chessboard images
          rm images/chessboard*.png

          # generate new chessboard image
          python scripts/export_chessboard.py $COMMENT_BODY

          # rename file to chessboard.png + timestamp
          TIMESTAMP=-$(date +%s)
          mv images/chessboard.png images/chessboard$TIMESTAMP.png 

          # update image link in readme
          sed -i "s|\(https://raw.githubusercontent.com/thieleju/thieleju/main/images/chessboard\)[^\" ]*|\1$TIMESTAMP.png|g" README.md

          # add Filename to github_env
          echo "CHESSBOARD_FILENAME=images/chessboard$TIMESTAMP.png" >> $GITHUB_ENV

      - name: Edit issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "![chessboard](https://raw.githubusercontent.com/thieleju/thieleju/main/${{ env.CHESSBOARD_FILENAME }})"
            })

      - name: Update readme link and commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .
          git commit -m "🚀 Update chessboard image, fen and readme"
          git push origin HEAD

      - name: Remove comment that triggered workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.deleteComment({
              comment_id: "${{ github.event.comment.id }}",
              owner: context.repo.owner,
              repo: context.repo.repo
            })
