name: Manual Test Workflow

on:
  workflow_dispatch:

jobs:
  test-python-setup:
    name: Test Python Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Display Python version
        run: python --version

      - name: Display Pip version
        run: pip --version
